modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Persistent%20Inventory%20Search"
logoFile="icon.png"

[[mods]]
modId="persistentinventorysearch"
version="1.2"
displayName="Persistent Inventory Search"
displayURL="https://curseforge.com/minecraft/mc-mods/persistent-inventory-search"
authors="Rick South"
description='''Makes search queries inside the creative inventory persistent, even after switching tabs and closing the inventory.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.persistentinventorysearch]]
    modId="collective"
    mandatory=true
    versionRange="[7.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.persistentinventorysearch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "persistentinventorysearch_neoforge.mixins.json"